{% set version = "7.2" %}

package:
  name: zope.interface
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/z/zope.interface/zope.interface-{{ version }}.tar.gz
  sha256: 8b49f1a3d1ee4cdaf5b32d2e738362c7f5e40ac8b46dd7d1a65e82a4872728fe

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - zope
    - zope.interface
    - zope.interface.common
    - zope.interface.common.tests
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations  # [python_impl != "pypy"]
    - zope.interface.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL-2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of object interfaces for Python.Interfaces are objects
    that specify the external behavior of objects that provide them.
  doc_url: http://docs.zope.org/zope.interface/
  doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.interface

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
