{% set version = "7.1.1" %}

package:
  name: zope.interface
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/z/zope.interface/zope.interface-{{ version }}.tar.gz
  sha256: 4284d664ef0ff7b709836d4de7b13d80873dc5faeffc073abdb280058bfac5e3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - zope
    - zope.interface
    - zope.interface.common
    - zope.interface.common.tests
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations  # [python_impl != "pypy"]
    - zope.interface.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL-2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of object interfaces for Python.Interfaces are objects
    that specify the external behavior of objects that provide them.
  doc_url: http://docs.zope.org/zope.interface/
  doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.interface

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
