{% set version = "4.7.1" %}

package:
  name: zope.interface
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/z/zope.interface/zope.interface-{{ version }}.tar.gz
  sha256: 4bb937e998be9d5e345f486693e477ba79e4344674484001a0b646be1d530487

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zope
    - zope.interface
    - zope.interface.common
    - zope.interface.common.tests
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations
    - zope.interface.tests

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL 2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of object interfaces for Python.Interfaces are objects
    that specify the external behavior of objects that provide them.
  doc_url: http://docs.zope.org/zope.interface/
  doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.interface

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
